# COVID-19 PANDEMIC

Discussion Topic: COVID-19 pandemic; Advances in epidemiological modelling and risk communication.

In [1]:
#Importing relevant libraries

import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# Extracting the covid.zip
import zipfile
import os

# Specify the path to your zip file
zip_file_path = r'C:\Users\USER PC\Documents\Practisw\COVID-19\Covid-19-Pandemic\covid.zip'
# Specify the name of the file inside the zip archive
csv_file_name = 'COVID-19 Coronavirus.csv'

# Read the CSV file directly from the zip file
with zipfile.ZipFile(zip_file_path, 'r') as z:
    with z.open(csv_file_name) as f:
        df = pd.read_csv(f)

# Now df contains the data from the CSV file
df.head(10)

,Country,Other names,ISO 3166-1 alpha-3 CODE,Population,Continent,Total Cases,Total Deaths,Tot Cases//1M pop,Tot Deaths/1M pop,Death percentage
0,Afghanistan,Afghanistan,AFG,40462186,Asia,177827,7671,4395,190,4.313743
1,Albania,Albania,ALB,2872296,Europe,273870,3492,95349,1216,1.275058
2,Algeria,Algeria,DZA,45236699,Africa,265691,6874,5873,152,2.587216
3,Andorra,Andorra,AND,77481,Europe,40024,153,516565,1975,0.382271
4,Angola,Angola,AGO,34654212,Africa,99194,1900,2862,55,1.915438
5,Anguilla,Anguilla,AIA,15237,Latin America and the Caribbean,2700,9,177200,591,0.333333
6,Antigua and Barbuda,Antigua and Barbuda,ATG,99348,Latin America and the Caribbean,7493,135,75422,1359,1.801682
7,Argentina,Argentina,ARG,45921761,Latin America and the Caribbean,9041124,128065,196881,2789,1.416472
8,Armenia,Armenia,ARM,2972939,Asia,422574,8617,142140,2898,2.039169
9,Aruba,Aruba,ABW,107560,Latin America and the Caribbean,34051,212,316577,1971,0.622596

In [11]:
# Repeat the same process for the remaining zip files
import zipfile
import os

# Specify the path to your zip file
zip_file_path = r'C:\Users\USER PC\Documents\Practisw\COVID-19\Covid-19-Pandemic\covid2.zip'
# Specify the name of the file inside the zip archive
csv_file_name = 'Covid Live.csv'

# Read the CSV file directly from the zip file
with zipfile.ZipFile(zip_file_path, 'r') as a:
    with a.open(csv_file_name) as b:
        df2 = pd.read_csv(b)
        
        
import zipfile
import os

# Specify the path to your zip file
zip_file_path = r'C:\Users\USER PC\Documents\Practisw\COVID-19\Covid-19-Pandemic\cov3.zip'
# Specify the name of the file inside the zip archive
csv_file_name = 'covid_19_clean_complete new.csv'

# Read the CSV file directly from the zip file
with zipfile.ZipFile(zip_file_path, 'r') as p:
    with p.open(csv_file_name) as g:
        df3 = pd.read_csv(g)

In [17]:
import zipfile
import os

# Specify the path to your zip file
zip_file_path = r'C:\Users\USER PC\Documents\Practisw\COVID-19\Covid-19-Pandemic\archive (10).zip'
# Specify the name of the file inside the zip archive
csv_file_name = 'open_one_time_covid_education_impact.csv'

# Read the CSV file directly from the zip file
with zipfile.ZipFile(zip_file_path, 'r') as z:
    with z.open(csv_file_name) as f:
        df4 = pd.read_csv(f)
        
df4.head(7)

,submission_id,submission_date,gender,age,geography,financial_situation,education,employment_status,submission_state,are_there_children_0_to_2_yrs_out_of_educational_system,...,are_children_3_to_17_yrs_dealing_with_irregular_school_activity,are_children_being_teached_by_unqualified_people,did_teachers_leave_the_educational_system,do_school_and_the_teachers_have_internet_connection,do_children_have_internet_connection,do_children_3_to_17_yrs_miss_virtual_class_due_to_lack_of_electricity,does_home_shows_severe_deficit_of_electricity,does_home_shows_severe_deficit_of_internet,do_children_3_to_17_yrs_miss_class_or_in_lower_grade,are_children_promoted_with_a_modality_different_from_formal_evaluation
0,4570534489882624,2021-03-17,Female,Over 45 years old,Suburban/Peri-urban,"I can afford food and regular expenses, but no...",University or college degree completed,I am unemployed,Miranda,0,...,0,0,0,1,1,0,0,0,0,0
1,6440166989496320,2021-03-29,Male,26 to 35 years old,Suburban/Peri-urban,I cannot afford enough food for my family,University or college degree completed,I am unemployed,Miranda,0,...,1,0,1,0,1,1,0,0,0,0
2,5001167808757760,2021-03-18,Female,26 to 35 years old,City center or metropolitan area,"I can comfortably afford food, clothes, and fu...",University or college degree completed,"I work full-time, either as an employee or sel...",Miranda,1,...,1,1,1,0,1,0,1,0,0,1
3,5524933164924928,2021-03-24,Male,36 to 45 years old,Suburban/Peri-urban,"I can afford food, but nothing else",University or college degree completed,"I work full-time, either as an employee or sel...",Miranda,0,...,1,1,1,0,1,0,0,0,0,0
4,5032515751641088,2021-03-18,Female,Over 45 years old,Suburban/Peri-urban,"I can afford food and regular expenses, but no...",University or college degree completed,I am unemployed,Miranda,0,...,1,0,1,0,1,1,0,0,0,1
5,5856891153678336,2021-03-15,Female,36 to 45 years old,City center or metropolitan area,"I can comfortably afford food, clothes, and fu...",Technical school diploma or degree completed,"I work full-time, either as an employee or sel...",Miranda,0,...,0,1,1,1,0,0,0,0,0,1
6,4994446973468672,2021-03-31,Female,26 to 35 years old,Rural,"I can afford food and regular expenses, but no...",University or college degree completed,"I do housework, fulfilling domestic tasks, loo...",Miranda,0,...,1,0,0,1,1,0,0,0,0,0